-- insert into Usuario () values(1, 'Camila96','camila','perez','alaniz','24','625896354','calle sin numero 3','madrid','madrid','56325');
-- insert into Usuario values(2, 'C5','camila','perez','alaniz','24','625896354','calle sin numero 3','madrid','madrid','56325');

-- El orden debería ser éste (copiado y pegado del log) Hibernate: create table usuario (id bigint generated by default as identity, apellido1 varchar(255), apellido2 varchar(255), ciudad varchar(255), codigo_postal integer not null, contrasena varchar(255), direccion varchar(255), edad integer not null, nombre varchar(255), nombre_usu varchar(255), provincia varchar(255), telefono integer not null, administrador_id bigint, primary key (id))
